name: pkg.pr.new

on:
  pull_request:

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: npx pkg-pr-new publish --bin --packageManager=bun
